FROM python:3.6-slim

RUN apt-get update
RUN apt-get install -y latexmk
RUN apt-get install -y texlive-full
RUN apt-get install -y git

COPY requirements.txt ./
RUN pip install $(cat requirements.txt)

WORKDIR /repos
RUN git clone https://github.com/CD3/pyErrorProp
WORKDIR pyErrorProp
RUN python ./setup.py install

WORKDIR /repos
RUN git clone https://github.com/CD3/macro_expander
WORKDIR macro_expander
RUN python ./setup.py install

WORKDIR /home/testenv
COPY test_repo.sh ./
CMD ./test_repo.sh
